kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: mimir
      type: prometheus
      access: proxy
      url: {{ .Values.global.mimirurl | quote }}/prometheus
      isDefault: true
      jsonData:
        httpMethod: POST
