apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-mimir-config
data:
  grafana-mimir.yaml: |-
  
    multitenancy_enabled: false

    blocks_storage:
      backend: filesystem
      bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync
      filesystem:
        dir: /tmp/mimir/data/tsdb
      tsdb:
        dir: /tmp/mimir/tsdb

    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist

    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 1

    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /tmp/mimir/rules
    activity_tracker:
      filepath: /tmp/metrics-activity.log

    server:
      http_listen_port: 9009
      log_level: debug
      grpc_server_max_send_msg_size: 8388608
      grpc_server_max_recv_msg_size: 8388608

    store_gateway:
      sharding_ring:
        replication_factor: 1
