apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.fullname" . }}-config
data:
  otel_collector_config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"  # Ensure this port is open
            tls:
              cert_file: /etc/tls/tls.crt
              key_file: /etc/tls/tls.key
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      debug:
        verbosity: detailed
      logging:  # Optional: log metrics for debugging
        loglevel: debug
      otlphttp/mimir:
        endpoint: {{ .Values.global.mimirurl }}/oltp
      prometheusremotewrite:
        endpoint: {{ .Values.global.mimirurl }}/api/v1/push

    processors:
      batch:
        timeout: 10s

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,debug,prometheusremotewrite]
